### ISSUE TITLE
AttributeError: 'Series' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by Siddhu2502** [stehrbaer/Evaluating-Soft-Actor-Critic-Agent-Performance-of-Equity-Trading-using-FinRL-#1]
In the last cell for plotting the output 

```python
print("Comparion to Benchmark (NASDAQ)")
%matplotlib inline
# S&P 500: ^GSPC
# Dow Jones Index: ^DJI
# NASDAQ 100: ^NDX
backtest_plot(
             df_account_value, 
             baseline_ticker = '^NDX', 
             baseline_start = df_account_value.loc[0,'date'],
             baseline_end = df_account_value.loc[len(df_account_value)-1,'date'])
```

running this cell causes this issue 

```
/usr/local/lib/python3.10/dist-packages/finrl/plot.py:67: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  baseline_df = baseline_df.fillna(method="ffill").fillna(method="bfill")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-47-76b47578ea15>](https://localhost:8080/#) in <cell line: 6>()
      4 # Dow Jones Index: ^DJI
      5 # NASDAQ 100: ^NDX
----> 6 backtest_plot(
      7              df_account_value,
      8              baseline_ticker = '^NDX',

5 frames
[/usr/local/lib/python3.10/dist-packages/finrl/plot.py](https://localhost:8080/#) in backtest_plot(account_value, baseline_start, baseline_end, baseline_ticker, value_col_name)
     69 
     70     with pyfolio.plotting.plotting_context(font_scale=1.1):
---> 71         pyfolio.create_full_tear_sheet(
     72             returns=test_returns, benchmark_rets=baseline_returns, set_context=False
     73         )

[/usr/local/lib/python3.10/dist-packages/pyfolio/tears.py](https://localhost:8080/#) in create_full_tear_sheet(returns, positions, transactions, market_data, benchmark_rets, slippage, live_start_date, sector_mappings, bayesian, round_trips, estimate_intraday, hide_positions, cone_std, bootstrap, unadjusted_returns, style_factor_panel, sectors, caps, shares_held, volumes, percentile, turnover_denom, set_context, factor_returns, factor_loadings, pos_in_dollars, header_rows, factor_partitions)
    199                                      positions, transactions)
    200 
--> 201     create_returns_tear_sheet(
    202         returns,
    203         positions=positions,

[/usr/local/lib/python3.10/dist-packages/pyfolio/plotting.py](https://localhost:8080/#) in call_w_context(*args, **kwargs)
     52                 return func(*args, **kwargs)
     53         else:
---> 54             return func(*args, **kwargs)
     55     return call_w_context
     56 

[/usr/local/lib/python3.10/dist-packages/pyfolio/tears.py](https://localhost:8080/#) in create_returns_tear_sheet(returns, positions, transactions, live_start_date, cone_std, benchmark_rets, bootstrap, turnover_denom, header_rows, return_fig)
    494         returns = utils.clip_returns_to_benchmark(returns, benchmark_rets)
    495 
--> 496     plotting.show_perf_stats(returns, benchmark_rets,
    497                              positions=positions,
    498                              transactions=transactions,

[/usr/local/lib/python3.10/dist-packages/pyfolio/plotting.py](https://localhost:8080/#) in show_perf_stats(returns, factor_returns, positions, transactions, turnover_denom, live_start_date, bootstrap, header_rows)
    646 
    647     for column in perf_stats.columns:
--> 648         for stat, value in perf_stats[column].iteritems():
    649             if stat in STAT_FUNCS_PCT:
    650                 perf_stats.loc[stat, column] = str(np.round(value * 100,

[/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py](https://localhost:8080/#) in __getattr__(self, name)
   6297         ):
   6298             return self[name]
-> 6299         return object.__getattribute__(self, name)
   6300 
   6301     @final

AttributeError: 'Series' object has no attribute 'iteritems'
```

could be a help if this issue is fixed or any possible solution for this is provied

## What i have tried is 
- Change the .iteritems() -> .items() in plotting.py 
=> still same issue occured
- Downgraded pandas -> to < 1.0
=> still no change

**Comment by Siddhu2502** [comment]
@stehrbaer can you please provide a solution ?

**Comment by Siddhu2502** [comment]
## Fix Found:

### downgrade pandas to lower version to 1.x.x versions (works fine with 1.5.3) tested 

```
!pip install pandas==1.5.3
```
